export default function CreatedEvent() {
  return (
    <>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
      <div>CreatedEvent</div>
    </>
  );
}
